version: "3.9"

services:
  ################################
  # MongoDB
  ################################
  mongo:
    image: mongo:6.0
    container_name: "mongo_db_container"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - mvp-net

  ################################
  # Backend (FastAPI)
  ################################
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: "backend"
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Si quieres redefinir MONGO_URI a mano, lo harías en environment:
    # environment:
    #   MONGO_URI: "mongodb://root:example@mongo:27017"
    volumes:
      - ./scraper:/app/scraper:ro  # si quieres montar tu folder scraper en read-only
    networks:
      - mvp-net

  ################################
  # Frontend (Streamlit)
  ################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    depends_on:
      - backend
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - mvp-net

volumes:
  mongo_data:
    driver: local

networks:
  mvp-net:
    driver: bridge
